# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d5b9e7d977d70614c76700342a25d93e68aff5f0a90d3a0a695776a889c88dd204ec4bfa289ea7414da069a97cce386646e9c2bfac188b8457727bd4a618547

test:
  secret_key_base: 1e1dba28d5018749878b0f17b244ede322c7c02701743864917254b2920dc4f5ba6e4ff64b078e65d0ed29d91f1d9e287bfe17e40802c3e51778656ea6f26989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
